# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicativo',
            name='url',
            field=models.URLField(default='htt://'),
            preserve_default=False,
        ),
    ]
