# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicativo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicativo',
            name='color',
            field=models.CharField(default='fff', max_length=10),
            preserve_default=False,
        ),
    ]
