# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_applicativo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicativo',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicativo',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicativo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicativo',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='applicativo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
