# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170130_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicativo',
            name='description',
            field=models.TextField(default='--'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicativo',
            name='textcolor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
