# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170130_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicativo',
            name='img',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
