# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_applicativo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicativo',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
