# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_applicativo_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('textcolor', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('img', models.TextField()),
                ('pic', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('urlpart', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='confapplicativo',
            name='applicativo',
        ),
        migrations.RemoveField(
            model_name='confapplicativo',
            name='usr',
        ),
        migrations.DeleteModel(
            name='Applicativo',
        ),
        migrations.DeleteModel(
            name='ConfApplicativo',
        ),
        migrations.AddField(
            model_name='application',
            name='urlmode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UrlMode'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled', to='core.Application'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
