# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20170515_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_claims', to='core.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('json', 'JSON Object'), ('array|int', 'Array of integer'), ('array|str', 'Array of string')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClaimType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appclaim',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClaimType'),
        ),
    ]
